// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateElapsedTime(arg1) {
  return window['go']['main']['App']['CalculateElapsedTime'](arg1);
}

export function Wedding(arg1) {
  return window['go']['main']['App']['Wedding'](arg1);
}
